version: '2'

services:
  bot:
    build: .
    depends_on:
      - api
      - redis
    ports:
      -  "5100:5100"
  api:
    build: ../youpin-api
    ports:
      -  "9100:9100"
    depends_on:
      - mongodb
  mongodb:
    image: mongo
  redis:
    image: redis
